stopwords = {'although', 'another', 'about', 'what', 'several', 'just', 'have', 'hereupon', 'less', 'ourselves',
             'almost', 'top', 'and', 'using', 'your', 'all', 'anything', 'they', 'very', 'thus', 'becoming', 'his',
             'none', 'therefore', 'hereafter', 'really', 'show', 'take', 'that', 'those', 'together', 'until',
             'besides', 'under', 'nowhere', 'yourselves', 'serious', 'everything', 'elsewhere', 'some', 'twelve',
             'anyone', 'for', 'us', 'across', 'nine', 'either', 'my', 'never', 'anywhere', 'due', 'such', 'thence',
             'first', 'these', 'seemed', 'why', 'you', 'this', 'keep', 'own', 'against', 'above', 'her', 'nothing',
             'while', 'who', 'could', 'give', 'meanwhile', 'therein', 'seeming', 'except', 'was', 'go', 'must',
             'myself', 'over', 'herself', 'nor', 'onto', 'beforehand', 'seems', 'anyhow', 'below', 'full', 'somehow',
             'still', 'various', 'back', 'move', 'hereby', 'via', 'where', 'get', 'does', 'whereas', 'how', 'rather',
             'see', 'he', 'someone', 'three', 'among', 'mine', 'seem', 'only', 'sixty', 'within', 'empty', 'others',
             'becomes', 'amongst', 'ten', 'beyond', 'ours', 'ca', 'everyone', 'next', 'whole', 'every', 'same', 'as',
             'front', 'at', 'six', 'latter', 'from', 'thereafter', 'other', 'throughout', 'wherever', 'no', 'ever',
             'forty', 'them', 'there', 'i', 'nevertheless', 'somewhere', 'with', 'make', 'an', 'side', 'sometime',
             'please', 'yourself', 'per', 'five', 'me', 'unless', 'because', 'sometimes', 'alone', 'everywhere',
             'hence', 'by', 'behind', 'in', 'name', 'now', 'though', 'their', 'two', 'during', 'whereby', 'third',
             'most', 'herein', 'him', 'she', 'a', 'without', 'since', 'on', 'often', 'more', 'twenty', 'eleven', 'much',
             'whoever', 'however', 'we', 'toward', 'last', 'beside', 'is', 'cannot', 'already', 'four', 'neither',
             'nobody', 'once', 'quite', 'least', 'put', 'been', 'off', 'should', 'upon', 'something', 'always',
             'whereafter', 'yours', 'itself', 'noone', 'after', 'our', 'done', 'or', 'indeed', 'it', 'thereupon',
             'else', 'then', 'of', 'anyway', 'if', 'any', 'being', 'the', 'wherein', 'did', 'call', 'whereupon',
             'whither', 'perhaps', 'yet', 'say', 'will', 'doing', 'otherwise', 'has', 'too', 'whatever', 'can',
             'whence', 'even', 'many', 'latterly', 'enough', 'fifty', 'moreover', 'so', 'part', 'down', 'namely', 'to',
             'had', 'here', 'both', 'than', 'before', 'eight', 'made', 'thru', 'themselves', 'thereby', 'towards',
             'whether', 'through', 'become', 'along', 'would', 'regarding', 'were', 'but', 'few', 'afterwards',
             'became', 'himself', 'between', 'do', 'its', 'also', 'amount', 'are', 'mostly', 'when', 'fifteen', 'out',
             'whenever', 'which', 'hundred', 'further', 'may', 'used', 'not', 'whose', 'formerly', 're', 'each', 'whom',
             'around', 'am', 'bottom', 'well', 'might', 'again', 'former', 'into', 'one', 'hers', 'be', 'up'}
